require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/importmap.rb"
    - "db/**/*"
    - "lib/tasks/*"
    - "vendor/ruby/**/*"
    - "vendor/bundle/**/*"
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

RSpec/FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%I": "()"
    "%w": "()"
    "%W": "()"

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/MultipleExpectations:
  Max: 25

RSpec/ExampleLength:
  Max: 100

Lint/MissingSuper:
  Enabled: false
