version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: dev
        tty: true
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - .:/code
        depends_on:
            - database
            - redis

    database:
        image: postgres:14
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=code_development
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    redis:
        image: redis:7
        ports:
            - 6379:6379
    chrome:
        image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
        volumes:
            - /dev/shm:/dev/shm
    
    ci: &ci
        build:
            context: .
            dockerfile: ./Dockerfile
            target: build
        volumes:
            - .:/code

    rubocop:
        <<: *ci
        command: "bundle exec rubocop"

    rspec:
        <<: *ci
        command: "bin/rspec-ci"
        user: "root"
        depends_on:
            - database
            - redis
            - chrome

    

volumes:
    db:
