# fly.toml file generated for boardgamecompanion on 2023-04-09T20:47:25-05:00

app = "boardgamecompanion"
primary_region = "dfw"

[env]

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  force_https = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[checks]
  [checks.alive]
  type = "tcp"
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
