require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/faces", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Face. As you add validations to Face, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Face.create! valid_attributes
      get faces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      face = Face.create! valid_attributes
      get face_url(face)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_face_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      face = Face.create! valid_attributes
      get edit_face_url(face)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Face" do
        expect {
          post faces_url, params: { face: valid_attributes }
        }.to change(Face, :count).by(1)
      end

      it "redirects to the created face" do
        post faces_url, params: { face: valid_attributes }
        expect(response).to redirect_to(face_url(Face.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Face" do
        expect {
          post faces_url, params: { face: invalid_attributes }
        }.to change(Face, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post faces_url, params: { face: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested face" do
        face = Face.create! valid_attributes
        patch face_url(face), params: { face: new_attributes }
        face.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the face" do
        face = Face.create! valid_attributes
        patch face_url(face), params: { face: new_attributes }
        face.reload
        expect(response).to redirect_to(face_url(face))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        face = Face.create! valid_attributes
        patch face_url(face), params: { face: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested face" do
      face = Face.create! valid_attributes
      expect {
        delete face_url(face)
      }.to change(Face, :count).by(-1)
    end

    it "redirects to the faces list" do
      face = Face.create! valid_attributes
      delete face_url(face)
      expect(response).to redirect_to(faces_url)
    end
  end
end
