name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run docker compose rubocop
        run: docker-compose run rubocop
