name: RuboCop

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run docker compose rubocop
        run: docker-compose run rubocop
  
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run docker compose rspec
        run: docker-compose run rspec
